# Generated by Django 5.1.6 on 2025-02-18 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_produto_imagem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='imagem',
        ),
    ]
