# Generated by Django 5.1.6 on 2025-02-19 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_produto_imagem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='imagem',
        ),
    ]
