# Generated by Django 5.1.6 on 2025-02-19 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_produto_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='produtos/', verbose_name='imagem'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='descricao',
            field=models.TextField(default='Descrição padrão', verbose_name='descrição'),
        ),
    ]
