# Generated by Django 5.1.6 on 2025-02-19 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_produto_imagem_alter_produto_descricao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='imagem',
        ),
        migrations.AlterField(
            model_name='produto',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
