# Generated by Django 5.1.6 on 2025-02-19 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_produto_imagem_alter_produto_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='produtos/', verbose_name='imagem'),
        ),
    ]
